# Generated by Django 2.2 on 2021-04-01 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50, verbose_name='модель')),
                ('serial', models.CharField(max_length=50, verbose_name='серийный номер')),
                ('year_of_buy', models.DateField(blank=True, null=True, verbose_name='Дата приобретения')),
                ('comment', models.TextField(default='', max_length=2000, verbose_name='Примечание')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='состояние')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_repair', models.DateField(verbose_name='Дата отправки')),
                ('problem', models.TextField(max_length=1000, verbose_name='Неисправность')),
                ('contractor', models.CharField(max_length=30, verbose_name='Исполнитель')),
                ('end_date_repair', models.DateField(verbose_name='Дата возврата')),
                ('result', models.TextField(max_length=1000, verbose_name='Результат ремонта')),
                ('cost', models.IntegerField(verbose_name='Стоимость ремонта')),
                ('hardware', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='hardware', to='base.Hardware', verbose_name='Оборудование')),
            ],
        ),
        migrations.AddField(
            model_name='hardware',
            name='manufacturer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='hardware', to='base.Manufacturer', verbose_name='производитель'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='place',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='hardware', to='base.Place', verbose_name='расположение'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='status',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='hardware', to='base.Status', verbose_name='состояние'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='hardware', to='base.Type', verbose_name='тип'),
        ),
    ]
