# Generated by Django 2.2 on 2021-04-01 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hardware',
            name='year_of_buy',
        ),
    ]
