# Generated by Django 2.2 on 2021-04-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_hardware_year_of_buy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repair',
            name='cost',
            field=models.IntegerField(null=True, verbose_name='Стоимость ремонта'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='date_repair',
            field=models.DateField(null=True, verbose_name='Дата отправки'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='end_date_repair',
            field=models.DateField(null=True, verbose_name='Дата возврата'),
        ),
    ]
